name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: laraveldemo
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install rsync -y

      - name: Deploy code to EC2 instance
        run: |
          rsync -rav -e "ssh -o StrictHostKeyChecking=no" --exclude='.git/' --exclude='.github/' --exclude='.env' ./ ec2-user@<EC2 instance public IP or hostname>:/path/to/laravel
          ssh ec2-user@<16.16.139.98> "sudo cd /var/www/html/laravelCICD/ && sudo chown -R www-data:www-data storage bootstrap/cache && php artisan cache:clear && php artisan config:cache"

      - name: Send Slack notification
        if: ${{ job.status == 'success' }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_COLOR: good
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_TITLE: 'Laravel application deployment successful!'
          SLACK_MESSAGE: 'The Laravel application has been deployed to the EC2 instance.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
